version: "3.7"

services:
  baka_api:
    build: .
    container_name: baka_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    depends_on:
      - baka_api_db
  baka_api_db:
    image: library/postgres:12.1
    environment:
      PGUSER: alphauser
      PGPASSWORD: alphapassword
      POSTGRES_USER: alphauser
      POSTGRES_PASSWORD: alphapassword
      POSTGRES_DB: baka_api_development
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data