version: "3.7"

services:
  baka_api:
    build: .
    container_name: baka_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: 'redis:6.2.1-alpine'
    command: 'redis-server'
    volumes:
      - '.:/app'
    ports:
      - '6379:6379'
  sidekiq:
    command: sidekiq
    volumes:
      - '.:/app'
    build: .
    env_file:
      - '.env'
    depends_on:
      - baka_api
      - redis