# frozen
WEEKLY_WORKING_HOURS = 40.freeze

STANDARD_DAILY_WORKING_HOURS = 8.freeze

MINIMUM_BREAK_HOURS = 11.freeze

MINIMUM_BREAK_HOURS_UNDERAGE = 12.freeze

MAX_SHIFT_DURATION_HOURS  = 12.freeze

SCHEDULER_TYPES = {
    SYSTEM: 1,
    MANAGER: 2,
    EMPLOYEE: 3
}.freeze