default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

production:
  <<: *default
  database: baka_api

development:
  <<: *default
  database: app_development

local:
  <<: *default
  host: localhost
  database: baka_api_development
  port: 5433

test:
  <<: *default
  host: localhost
  database: baka_api_test
  port: 5433
